name: microuns  # overridden at install, so this is for your use with conda env
channels:
  - anaconda
  - https://conda.anaconda.org/menpo
dependencies:
  - scipy=0.16.1
  - scikit-image=0.11.3
  - Flask=0.10.1
  - opencv=2.4.11