name: microuns  # overridden at install, so this is for your use with conda env
channels:
  - anaconda
  - https://conda.anaconda.org/menpo
dependencies:
  - scipy
  - scikit-image==0.11.3
  - Flask==0.10.1
  - opencv